/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.LoaiGiayRepository;

/**
 *
 * @author Legion
 */
public class LoaiGiay extends javax.swing.JPanel {

    private LoaiGiayRepository lgRepo;
    private DefaultTableModel dtm;

    /**
     * Creates new form LoaiGiay
     */
    public LoaiGiay() {
        initComponents();
        this.lgRepo = new LoaiGiayRepository();
        loadTableLG();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_loaiGiay = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_loaiGiay = new javax.swing.JTable();

        jLabel1.setText("Tên");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sưa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        tbl_loaiGiay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên Loại Giày"
            }
        ));
        tbl_loaiGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loaiGiayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_loaiGiay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_them)
                                .addGap(33, 33, 33)
                                .addComponent(btn_sua)
                                .addGap(32, 32, 32)
                                .addComponent(btn_xoa)
                                .addGap(41, 41, 41)
                                .addComponent(btn_lamMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(59, 59, 59)
                                .addComponent(txt_loaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_loaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_lamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_loaiGiayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loaiGiayMouseClicked
        this.btn_them.setEnabled(false);
        this.btn_sua.setEnabled(true);
        this.btn_xoa.setEnabled(true);

        int row = tbl_loaiGiay.getSelectedRow();

        if (row == -1) {
            return;
        }

        String ten = tbl_loaiGiay.getValueAt(row, 1).toString();

        this.txt_loaiGiay.setText(ten);
    }//GEN-LAST:event_tbl_loaiGiayMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String ten = this.txt_loaiGiay.getText().trim();

        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }
        int checkLg = lgRepo.checkTenCL(ten);
        if (checkLg != 0) {
            JOptionPane.showMessageDialog(this, "Tên loại giày đã tồn tại");
            return;
        }
        domainModels.LoaiGiay lg = new domainModels.LoaiGiay();
        lg.setTenLoaiGiay(ten);
        lgRepo.them(lg);
        loadTableLG();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String ten = this.txt_loaiGiay.getText().trim();

        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }

        int row = tbl_loaiGiay.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_loaiGiay.getValueAt(row, 0).toString());
        domainModels.LoaiGiay lg = lgRepo.findByMa(ma);
        lg.setTenLoaiGiay(ten);
        lgRepo.sua(lg);
        loadTableLG();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int row = tbl_loaiGiay.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_loaiGiay.getValueAt(row, 0).toString());
        int choose = JOptionPane.showConfirmDialog(this, "Có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.CLOSED_OPTION) {
            return;
        }
        domainModels.LoaiGiay lg = lgRepo.findByMa(ma);
        int checkXoaLg = lgRepo.checkTruocXoa(lg.getId());
        if (checkXoaLg != 0) {
            JOptionPane.showMessageDialog(this, "Loại giày này hiện đang liên kết với bảng chi tiết giày.\n Vui lòng xóa CT giày chứa loại giày này để xóa loại giày này");
            return;
        }
        lgRepo.xoa(lg.getId());
        loadTableLG();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        lamMoi2();
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void loadTableLG() {
        dtm = (DefaultTableModel) tbl_loaiGiay.getModel();

        dtm.setRowCount(0);

        List<domainModels.LoaiGiay> ds = lgRepo.getAll();

        if (ds == null) {
            return;
        }

        for (domainModels.LoaiGiay d : ds) {
            Object[] data = {
                d.getMaLoaiGiay(),
                d.getTenLoaiGiay()
            };

            dtm.addRow(data);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_loaiGiay;
    private javax.swing.JTextField txt_loaiGiay;
    // End of variables declaration//GEN-END:variables

    private void lamMoi2() {
        this.txt_loaiGiay.setText("");

        this.btn_them.setEnabled(true);
        this.btn_sua.setEnabled(false);
        this.btn_xoa.setEnabled(false);
    }
}
