/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import domainModels.ChatLieu;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.ChatLieuRepository;

/**
 *
 * @author Legion
 */
public class pnChatLieu extends javax.swing.JPanel {

    private ChatLieuRepository clRepo;
    private DefaultTableModel dtm;

    /**
     * Creates new form pnChatLieu
     */
    public pnChatLieu() {
        initComponents();
        this.clRepo = new ChatLieuRepository();
        loadTableCL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtCLDe = new javax.swing.JTextField();
        txtCLThan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCL = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();

        jLabel13.setText("Chất liệu đế:");

        jLabel14.setText("Chất liệu đế:");

        jLabel15.setText("Chất liệu thân:");

        tblCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Chất liệu đế", "Chất liệu thân"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCLMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCL);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_lammoi.setText("Làm Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCLDe)
                    .addComponent(txtCLThan, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_them)
                .addGap(30, 30, 30)
                .addComponent(btn_sua)
                .addGap(68, 68, 68)
                .addComponent(btn_xoa)
                .addGap(63, 63, 63)
                .addComponent(btn_lammoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCLDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCLThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_lammoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCLMouseClicked
        int row = tblCL.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tblCL.getValueAt(row, 0).toString());
        String de = tblCL.getValueAt(row, 1).toString();
        String than = tblCL.getValueAt(row, 2).toString();

        txtCLDe.setText(de);
        txtCLThan.setText(than);
        this.btn_them.setEnabled(false);
        this.btn_sua.setEnabled(true);
        this.btn_xoa.setEnabled(true);
    }//GEN-LAST:event_tblCLMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String de = txtCLDe.getText().trim();
        String than = txtCLThan.getText().trim();

        if (de.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống chất liệu đế");
            return;
        }

        if (than.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống chất liệu thân");
            return;
        }

        ChatLieu cl = new ChatLieu();
        cl.setChatLieuDe(de);
        cl.setChatLieuThan(than);
        clRepo.themCL(cl);
        lamMoi3();
        JOptionPane.showMessageDialog(this, "Add thành công");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
           int row = tblCL.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tblCL.getValueAt(row, 0).toString());
        String de = txtCLDe.getText().trim();
        String than = txtCLThan.getText().trim();

        if (de.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống chất liệu đế");
            return;
        }

        if (than.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống chất liệu thân");
            return;
        }

        ChatLieu cl = clRepo.findByMa(ma);
        cl.setChatLieuDe(de);
        cl.setChatLieuThan(than);
        clRepo.suaCL(cl);
        lamMoi3();
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int row = tblCL.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tblCL.getValueAt(row, 0).toString());
        int choose = JOptionPane.showConfirmDialog(this, "Có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.CLOSED_OPTION) {
            return;
        }
        ChatLieu cl = clRepo.findByMa(ma);
        int checkXoa = clRepo.checkTruocXoa(cl.getId());
        if (checkXoa == 0) {
            clRepo.xoaCL(cl.getId());
            lamMoi3();
            JOptionPane.showMessageDialog(this, "Xóa thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Chất liệu này hiện đang liên kết với bảng chi tiết giày.\n Vui lòng xóa CT giày chứa doanh mục này để xóa doanh mục này");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
       lamMoi3();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void lamMoi3() {
        txtCLDe.setText("");
        txtCLThan.setText("");
        btn_them.setEnabled(true);
        btn_xoa.setEnabled(false);
        btn_sua.setEnabled(false);
        loadTableCL();
    }

    private void loadTableCL() {
        dtm = (DefaultTableModel) tblCL.getModel();

        dtm.setRowCount(0);

        List<ChatLieu> ds = clRepo.getAll();

        if (ds == null) {
            return;
        }

        for (ChatLieu d : ds) {
            Object[] data = {
                d.getMaChatLieu(),
                d.getChatLieuThan(),
                d.getChatLieuDe()
            };

            dtm.addRow(data);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCL;
    private javax.swing.JTextField txtCLDe;
    private javax.swing.JTextField txtCLThan;
    // End of variables declaration//GEN-END:variables
}
