/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import domainModels.DanhMucSanPham;
import domainModels.Hang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.HangRepository;

/**
 *
 * @author Legion
 */
public class pnHang extends javax.swing.JPanel {
    private HangRepository hangRepo;
     private DefaultTableModel dtm;
    /**
     * Creates new form pnHang
     */
    public pnHang() {
        initComponents();
          this.hangRepo = new HangRepository();
          loadTableHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Hang = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hang = new javax.swing.JTable();

        jLabel1.setText("Tên Hãng");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        tbl_hang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Hãng", "Tên Hãng"
            }
        ));
        tbl_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_them))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Sua)
                                .addGap(45, 45, 45)
                                .addComponent(btn_xoa)
                                .addGap(42, 42, 42)
                                .addComponent(btn_lamMoi)))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_Sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_lamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
       String ten = this.txt_Hang.getText().trim();
        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }
        int checkDM = hangRepo.checkTen(ten);
        if (checkDM != 0) {
            JOptionPane.showMessageDialog(this, "Tên danh mục đã tồn tại");
            return;
        }
        Hang dm = new Hang();
        dm.setTenHang(ten);
        hangRepo.them(dm);
        loadTableHang();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        String ten = this.txt_Hang.getText().trim();
        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }
        int row = tbl_hang.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_hang.getValueAt(row, 0).toString());
         Hang h = hangRepo.findByMa(ma);
            h.setTenHang(ten);
            hangRepo.sua(h);
            loadTableHang();
            lamMoi2();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        
        int row = tbl_hang.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_hang.getValueAt(row, 0).toString());
        int choose = JOptionPane.showConfirmDialog(this, "Có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.CLOSED_OPTION) {
            return;
        }
        Hang h = hangRepo.findByMa(ma);
            int checkXoaH = hangRepo.checkTruocXoa(h.getId());
            if (checkXoaH != 0) {
                JOptionPane.showMessageDialog(this, "Hãng này hiện đang liên kết với bảng chi tiết giày.\n Vui lòng xóa CT giày chứa hãng này để xóa hãng này");
                return;
            }
            hangRepo.xoa(h.getId());
            loadTableHang();
            lamMoi2();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
      lamMoi2();
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void tbl_hangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hangMouseClicked
      this.btn_them.setEnabled(false);
        this.btn_Sua.setEnabled(true);
        this.btn_xoa.setEnabled(true);

        int row = tbl_hang.getSelectedRow();

        if (row == -1) {
            return;
        }

        String ten = tbl_hang.getValueAt(row, 1).toString();

        this.txt_Hang.setText(ten);

    }//GEN-LAST:event_tbl_hangMouseClicked
private void loadTableHang() {
        dtm = (DefaultTableModel) tbl_hang.getModel();

        dtm.setRowCount(0);

        List<Hang> ds = hangRepo.getAll();

        if (ds == null) {
            return;
        }

        for (Hang d : ds) {
            Object[] data = {
                d.getMaHang(),
                d.getTenHang()
            };

            dtm.addRow(data);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_hang;
    private javax.swing.JTextField txt_Hang;
    // End of variables declaration//GEN-END:variables

    private void lamMoi2() {
           this.txt_Hang.setText("");

        this.btn_them.setEnabled(true);
        this.btn_Sua.setEnabled(false);
        this.btn_xoa.setEnabled(false);
    }
}
