/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import domainModels.KhachHang;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.serviceKH;
import serviceImpl.implKH;
import viewModels.KhacHangViewModel;

/**
 *
 * @author ACER
 */
public class pnKH extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private implKH service = new serviceKH();
    ArrayList<KhacHangViewModel> list = new ArrayList<>();

    /**
     * Creates new form pnKH
     */
    public pnKH() {
        initComponents();
        list = service.getAll();
        getDta(service.getAll());

        tblbang.getColumnModel().getColumn(0).setMinWidth(0);
        tblbang.getColumnModel().getColumn(0).setMaxWidth(0);
        tblbang.getColumnModel().getColumn(0).setWidth(0);
    }

    public void getDta(ArrayList<KhacHangViewModel> list) {
        dtm = (DefaultTableModel) tblbang.getModel();
        dtm.setRowCount(0);
        for (KhacHangViewModel kh : list) {
            dtm.addRow(new Object[]{
                kh.getId(),
                kh.getMa(),
                kh.getHoTen(),
                kh.getNgaySinh(),
                kh.getGioiTinh(),
                kh.getSdt(),
                kh.getDiaChi(),
                kh.getEmail()
            });

        }
    }

    private void clearTblKH() {
        this.txtid.setText("");
        this.txtma.setText("");
        this.txtten1.setText("");
        this.txtngaysinh.setText("");
        this.txtSDT.setText("");
        this.txtDC.setText("");
        this.txtemail.setText("");
        this.txttim.setText("");
        this.buttonGroup1.clearSelection();
        getDta(service.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel12 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        txtSDT = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtDC = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtten1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        txttim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(1271, 300));
        jPanel12.setLayout(new java.awt.CardLayout());

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel23.setPreferredSize(new java.awt.Dimension(1271, 380));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Mã khách hàng");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Họ Tên khách hàng");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Giới tính");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("Số điện thoại");

        txtma.setEditable(false);
        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdonam);
        rdonam.setSelected(true);
        rdonam.setText("Nam");
        rdonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("Địa chỉ");

        txtDC.setColumns(20);
        txtDC.setRows(5);
        jScrollPane9.setViewportView(txtDC);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setForeground(new java.awt.Color(102, 255, 102));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm thông tin");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Xóa thông tin");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Sửa thông tin");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAdd)
                .addGap(26, 26, 26)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(44, 44, 44))
        );

        txtid.setEditable(false);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setText("ID khách hàng");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setText("Ngày Sinh");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setText("Email");

        txtten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtten1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39))
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(rdonam)
                                .addGap(52, 52, 52)
                                .addComponent(rdonu))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(txtma, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(txtten1))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtid)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel41)
                        .addComponent(jLabel58)
                        .addComponent(jLabel59)))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel57))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel58)
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtten1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel59)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel39)
                                    .addComponent(rdonam)
                                    .addComponent(rdonu))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addGap(0, 45, Short.MAX_VALUE))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jPanel12.add(jPanel23, "card2");

        add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã khách hàng", "Tên khách hàng", "Ngày Sinh", "Giới tính", "Số điện thoại", "Địa chỉ", "Email"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblbang);

        txttim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttimCaretUpdate(evt);
            }
        });
        txttim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tìm tên khách hàng");

        btnTim.setBackground(new java.awt.Color(204, 204, 204));
        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnin.setText("Export Excel");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                        .addComponent(btnin)
                        .addGap(18, 18, 18)
                        .addComponent(btnreset))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTim))
                    .addComponent(btnin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel11, "card2");

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtmaActionPerformed

    private void rdonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonamActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtten1.getText().equals("") || txtten1.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống tên khách hàng");
            return;
        }
        if (txtSDT.getText().equals("") || txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống số điện thoại khách hàng");
            return;
        }
        if (txtngaysinh.getText().equals("") || txtngaysinh.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày sinh khách hàng");
            return;
        }
        if (txtemail.getText().equals("") || txtemail.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống email khách hàng");
            return;
        }
        if (txtDC.getText().equals("") || txtDC.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống địa chỉ khách hàng");
            return;
        }
        String id = txtid.getText();
        KhachHang kh = new KhachHang();
        kh.setHoTen(txtten1.getText().trim());

        if (rdonam.isSelected()) {
            kh.setGioiTinh("Nam");
        } else {
            kh.setGioiTinh("Nữ");
        }

        if (txtSDT.getText().matches("^(03[2-9]|05[0-9]|07[0-9]|08[1-9]|09[0-9])\\d{7}$")) {
            kh.setSdt(txtSDT.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Số điện thoại nhập chưa đúng");
            return;
        }
        //validate ngày sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        try {
            Date ngaySinh = dateFormat.parse(txtngaysinh.getText());
            Date ngayHienTai = new Date();

            if (ngaySinh.after(ngayHienTai)) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không được sau ngày hiện tại.");
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh nhập chưa đúng định dạng (yyyy-MM-dd)");
            return;
        }
        if (txtngaysinh.getText().matches("^(19[7-9]\\d|20\\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
            kh.setNgaySinh(txtngaysinh.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Ngày sinh bắt đầu từ 1970 đến hiện tại!");
            return;
        }
        if (txtemail.getText().matches("\\w+@\\w+\\.\\w+")) {
            kh.setEmail(txtemail.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Email nhập chưa đúng");
            return;
        }
        kh.setDiaChi(txtDC.getText().trim());

        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
        if (xacNhan == 0) {

            service.them(kh);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            getDta(service.getAll());

        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = txtid.getText();
        int xacNhan = JOptionPane.showConfirmDialog(this, "ban co muon xoa k?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (xacNhan == 0) {
            int check = service.delete(id);

            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Không thể xóa!");

            } else {
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                getDta(service.getAll());
                clearTblKH();
            }

        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtten1.getText().equals("") || txtten1.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống tên khách hàng");
            return;
        }
        if (txtSDT.getText().equals("") || txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống số điện thoại khách hàng");
            return;
        }
        if (txtngaysinh.getText().equals("") || txtngaysinh.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày sinh khách hàng");
            return;
        }
        if (txtemail.getText().equals("") || txtemail.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống email khách hàng");
            return;
        }
        if (txtDC.getText().equals("") || txtDC.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống địa chỉ khách hàng");
            return;
        }
        String id = txtid.getText();
        KhachHang kh = new KhachHang();
        kh.setHoTen(txtten1.getText().trim());

        if (rdonam.isSelected()) {
            kh.setGioiTinh("Nam");
        } else {
            kh.setGioiTinh("Nữ");
        }

        if (txtSDT.getText().matches("^(03[2-9]|05[0-9]|07[0-9]|08[1-9]|09[0-9])\\d{7}$")) {
            kh.setSdt(txtSDT.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Số điện thoại nhập chưa đúng");
            return;
        }
        //validate ngày sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        try {
            Date ngaySinh = dateFormat.parse(txtngaysinh.getText());
            Date ngayHienTai = new Date();

            if (ngaySinh.after(ngayHienTai)) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không được sau ngày hiện tại.");
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh nhập chưa đúng định dạng (yyyy-MM-dd)");
            return;
        }
        if (txtngaysinh.getText().matches("^(19[7-9]\\d|20\\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
            kh.setNgaySinh(txtngaysinh.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Ngày sinh bắt đầu từ 1970 đến hiện tại!");
            return;
        }
        if (txtemail.getText().matches("\\w+@\\w+\\.\\w+")) {
            kh.setEmail(txtemail.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Email nhập chưa đúng");
            return;
        }
        kh.setDiaChi(txtDC.getText().trim());

        int xacNhan = JOptionPane.showConfirmDialog(this, "Ban co muon sua k?");
        if (xacNhan == 0) {

            service.update(kh, id);
            JOptionPane.showMessageDialog(this, "Sua thanh cong");
            getDta(service.getAll());

        } else {
            JOptionPane.showMessageDialog(this, "Sua that bai");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtten1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtten1ActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        int row = tblbang.getSelectedRow();
        if (row == -1) {
            return;
        }
        txtid.setText(tblbang.getValueAt(row, 0).toString());
        txtma.setText(tblbang.getValueAt(row, 1).toString());
        txtten1.setText(tblbang.getValueAt(row, 2).toString());
        txtngaysinh.setText(tblbang.getValueAt(row, 3).toString());
        String sex = this.tblbang.getValueAt(row, 4).toString();
        txtSDT.setText(tblbang.getValueAt(row, 5).toString());
        txtDC.setText(tblbang.getValueAt(row, 6).toString());
        txtemail.setText(tblbang.getValueAt(row, 7).toString());
        if (sex.equalsIgnoreCase("Nam")) {
            rdonam.setSelected(true);
        } else if (sex.equalsIgnoreCase("Nữ")) {
            rdonu.setSelected(true);
        }
    }//GEN-LAST:event_tblbangMouseClicked

    private void txttimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttimCaretUpdate

    }//GEN-LAST:event_txttimCaretUpdate

    private void txttimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKeyReleased
        String hoten = txttim.getText();

        ArrayList<KhacHangViewModel> kq = service.sreach(hoten);
        getDta(kq);

    }//GEN-LAST:event_txttimKeyReleased

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String hoten = txttim.getText();
        int xacNhan = JOptionPane.showConfirmDialog(this, "ban co muon tim k?");
        if (xacNhan == 0) {

            ArrayList<KhacHangViewModel> kq = service.sreach(hoten);
            JOptionPane.showMessageDialog(this, "tim thanh cong");
            getDta(kq);

        } else {
            JOptionPane.showMessageDialog(this, "tim that bai");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wordkbook = new XSSFWorkbook();
            XSSFSheet sheet = wordkbook.createSheet("danhsach");
            XSSFRow row = null;
            Cell cell = null;
            //        row=sheet.createRow(0);
            //        cell=row.createCell(0,CellType.STRING);
            //        cell.setCellValue("DANH SACH KHACH HANG");
            //
            //        row=sheet.createRow(1);
            //        cell=row.createCell(0,CellType.STRING);
            //        cell.setCellValue("STT");
            //
            //        cell=row.createCell(1,CellType.STRING);
            //        cell.setCellValue("ID");
            //
            //        cell=row.createCell(2,CellType.STRING);
            //        cell.setCellValue("MA");
            //
            //        cell=row.createCell(3,CellType.STRING);
            //        cell.setCellValue("HOTEN");
            //
            //        cell=row.createCell(4,CellType.STRING);
            //        cell.setCellValue("NGAYSINH");
            //
            //        cell=row.createCell(5,CellType.STRING);
            //        cell.setCellValue("GIOITINH");
            //
            //        cell=row.createCell(6,CellType.STRING);
            //        cell.setCellValue("SDT");
            //
            //        cell=row.createCell(7,CellType.STRING);
            //        cell.setCellValue("DIACHI");
            //
            //        cell=row.createCell(8,CellType.STRING);
            //        cell.setCellValue("EMAIL");

            list = service.getAll();
            for (int i = 0; i < list.size(); i++) {
                //Modelbook book =arr.get(i);
                row = sheet.createRow(i);

                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(list.get(i).getId());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(list.get(i).getMa());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(list.get(i).getHoTen());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(list.get(i).getNgaySinh());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(list.get(i).getGioiTinh());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(list.get(i).getSdt());

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(list.get(i).getDiaChi());

                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue(list.get(i).getEmail());
            }

            Random random = new Random();
            int min = 10;
            int max = 20;
            int randomNumber = random.nextInt(max - min + 1) + min;
            File f = new File("D://danhsachKH" + randomNumber + ".xlsx");
            try {
                FileOutputStream fis = new FileOutputStream(f);
                wordkbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();

            } catch (IOException ex) {
                ex.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "in thanh cong D:\\danhsach");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi mo file");
        }

    }//GEN-LAST:event_btninActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        clearTblKH();

    }//GEN-LAST:event_btnresetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnreset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextArea txtDC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtten1;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
