/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import domainModels.MauSac;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.MauSacRepository;
import java.awt.event.WindowEvent;

/**
 *
 * @author Legion
 */
public class pnMauSac extends javax.swing.JPanel {

    private MauSacRepository msRepo;
    private DefaultTableModel dtm;

    /**
     * Creates new form pnMauSac
     */
    public pnMauSac() {
        initComponents();
        this.msRepo = new MauSacRepository();
        loadTableMS();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_mauSac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mauSac = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();

        jLabel1.setText("Tên Màu Sắc");

        tbl_mauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Màu", "Tên Màu"
            }
        ));
        tbl_mauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mauSac);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm Mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)
                                .addComponent(txt_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_them)
                        .addGap(61, 61, 61)
                        .addComponent(btn_Sua)
                        .addGap(47, 47, 47)
                        .addComponent(btn_Xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_LamMoi)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_LamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_mauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mauSacMouseClicked
        this.btn_them.setEnabled(false);
        this.btn_Sua.setEnabled(true);
        this.btn_Xoa.setEnabled(true);

        int row = tbl_mauSac.getSelectedRow();

        if (row == -1) {
            return;
        }

        String ten = tbl_mauSac.getValueAt(row, 1).toString();

        this.txt_mauSac.setText(ten);
    }//GEN-LAST:event_tbl_mauSacMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String ten = this.txt_mauSac.getText().trim();

        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }
        int checkMS = msRepo.checkTen(ten);
        if (checkMS != 0) {
            JOptionPane.showMessageDialog(this, "Tên màu sắc đã tồn tại");
            return;
        }
        MauSac ms = new MauSac();
        ms.setTenMS(ten);
        msRepo.them(ms);
        loadTableMS();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        String ten = this.txt_mauSac.getText().trim();

        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống");
            return;
        }

        int row = tbl_mauSac.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_mauSac.getValueAt(row, 0).toString());
        MauSac ms = msRepo.findByMa(ma);
        ms.setTenMS(ten);
        msRepo.sua(ms);
        loadTableMS();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int row = tbl_mauSac.getSelectedRow();

        if (row == -1) {
            return;
        }

        int ma = Integer.parseInt(tbl_mauSac.getValueAt(row, 0).toString());
        int choose = JOptionPane.showConfirmDialog(this, "Có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.CLOSED_OPTION) {
            return;
        }
        MauSac ms = msRepo.findByMa(ma);

        int checkXoa = msRepo.checkTruocXoa(ms.getId());
        if (checkXoa != 0) {
            JOptionPane.showMessageDialog(this, "Màu sắc này hiện đang liên kết với bảng chi tiết giày.\n Vui lòng xóa CT giày chứa màu sắc này để xóa màu sắc này");
            return;
        }
        msRepo.xoa(ms.getId());
        loadTableMS();
        lamMoi2();
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        lamMoi2();
    }//GEN-LAST:event_btn_LamMoiActionPerformed
    private void loadTableMS() {
        dtm = (DefaultTableModel) tbl_mauSac.getModel();

        dtm.setRowCount(0);

        List<MauSac> ds = msRepo.getAll();

        if (ds == null) {
            return;
        }

        for (MauSac d : ds) {
            Object[] data = {
                d.getMaMS(),
                d.getTenMS()
            };

            dtm.addRow(data);
        }

    }
               
            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_mauSac;
    private javax.swing.JTextField txt_mauSac;
    // End of variables declaration//GEN-END:variables

    private void lamMoi2() {
        this.txt_mauSac.setText("");

        this.btn_them.setEnabled(true);
        this.btn_Sua.setEnabled(false);
        this.btn_Xoa.setEnabled(false);
    }
}
