/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import domainModels.NhanVien;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import serviceImpl.NhanVienServiceImpl;
import viewModels.NhanVienViewModel;

/**
 *
 * @author ACER
 */
public class pnNhanVien extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private NhanVienServiceImpl service = new NhanVienServiceImpl();
    ArrayList<NhanVienViewModel> list = new ArrayList<>();
    public String sdt = "", cccd = "", email = "";

    /**
     * Creates new form pnNhanVien
     */
    public pnNhanVien() {
        initComponents();
        this.getDta(service.getAll());

        tbl_nhanVien.getColumnModel().getColumn(0).setMinWidth(0);
    tbl_nhanVien.getColumnModel().getColumn(0).setMaxWidth(0);
    tbl_nhanVien.getColumnModel().getColumn(0).setWidth(0);
    }

    public void getDta(ArrayList<NhanVienViewModel> list) {
        dtm = (DefaultTableModel) tbl_nhanVien.getModel();
        dtm.setRowCount(0);
        for (NhanVienViewModel nv : list) {
            dtm.addRow(new Object[]{
                nv.getId(),
                nv.getMaNv(),
                nv.getHoTen(),
                nv.getGioiTinh(),
                nv.getNgaySinh(),
                nv.getSdt(),
                nv.getCccd(),
                nv.getDiaChi(),
                nv.getEmail(),
                nv.getChucVu(),
                nv.getMatKhau(),
                nv.getTrangThai() == 0 ? "Đang làm việc" : "Nghỉ việc"
            });

        }
    }

    public void Clear() {
        lbID2.setText("");
        lbMaNV.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtCCCD.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtMatKhau.setText("");
        cbbChucVu.setSelectedIndex(0);
        rdoNam.setSelected(true);
        rdoDangLamViec.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_nhanVien = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        btnQR = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        btnAddNhanVien = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        rdoNghiViec = new javax.swing.JRadioButton();
        rdoDangLamViec = new javax.swing.JRadioButton();
        txtDiaChi = new javax.swing.JTextField();
        lbID2 = new javax.swing.JLabel();
        btnin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbl_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã NV", "Họ Tên", "Giới Tính", "Ngày Sinh", "SĐT", "CCCD", "Địa chỉ", "Email", "Chức vụ", "Mật Khẩu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_nhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_nhanVien);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tìm tên nhân viên");

        txttim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttimCaretUpdate(evt);
            }
        });
        txttim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimKeyReleased(evt);
            }
        });

        btnQR.setText("Quét QR");
        btnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel9)
                .addGap(80, 80, 80)
                .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQR)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnQR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel10.setText("Họ & Tên nhân viên:");

        jLabel11.setText("Mã nhân viên:");

        jLabel13.setText("ID:");

        btnAddNhanVien.setText("Thêm");
        btnAddNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNhanVienActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel1.setText("Số điện thoại:");

        jLabel2.setText("Giới tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        jLabel3.setText("CCCD: ");

        jLabel4.setText("Trạng thái:");

        jLabel5.setText("Chức vụ:");

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Email:");

        jLabel8.setText("Ngày sinh:");

        buttonGroup2.add(rdoNghiViec);
        rdoNghiViec.setText("Nghỉ việc");

        buttonGroup2.add(rdoDangLamViec);
        rdoDangLamViec.setText("Đang làm việc");
        rdoDangLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDangLamViecActionPerformed(evt);
            }
        });

        btnin.setText("Export");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        jLabel12.setText("Mật Khẩu: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCCCD)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNu))
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi)
                                    .addComponent(txtEmail)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rdoDangLamViec)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNghiViec)
                                        .addGap(0, 240, Short.MAX_VALUE))
                                    .addComponent(txtMatKhau)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbID2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSDT)
                            .addComponent(jLabel12)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(rdoDangLamViec)
                        .addComponent(rdoNghiViec))
                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAddNhanVien)
                    .addComponent(btnin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_nhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanVienMouseClicked
// Mouse click
        int row = tbl_nhanVien.getSelectedRow();
        sdt = tbl_nhanVien.getValueAt(row, 5).toString();
        cccd = tbl_nhanVien.getValueAt(row, 6).toString();
        email = tbl_nhanVien.getValueAt(row, 8).toString();
        lbID2.setText(tbl_nhanVien.getValueAt(row, 0).toString());
        lbMaNV.setText(tbl_nhanVien.getValueAt(row, 1).toString());
        txtHoTen.setText(tbl_nhanVien.getValueAt(row, 2).toString());
        String gioiTinh = this.tbl_nhanVien.getValueAt(row, 3).toString();
        txtNgaySinh.setText(tbl_nhanVien.getValueAt(row, 4).toString());
        txtSDT.setText(tbl_nhanVien.getValueAt(row, 5).toString());
        txtCCCD.setText(tbl_nhanVien.getValueAt(row, 6).toString());
        txtDiaChi.setText(tbl_nhanVien.getValueAt(row, 7).toString());
        txtEmail.setText(tbl_nhanVien.getValueAt(row, 8).toString());
        cbbChucVu.setSelectedItem(tbl_nhanVien.getValueAt(row, 9).toString());
        txtMatKhau.setText(tbl_nhanVien.getValueAt(row, 10).toString());
        String trangThai = this.tbl_nhanVien.getValueAt(row, 11).toString();

        if (trangThai.equalsIgnoreCase("Đang Làm Việc")) {
            rdoDangLamViec.setSelected(true);
        } else if (trangThai.equalsIgnoreCase("Nghỉ việc")) {
            rdoNghiViec.setSelected(true);
        }

        if (gioiTinh.equalsIgnoreCase("Nam")) {
            rdoNam.setSelected(true);
        } else if (gioiTinh.equalsIgnoreCase("Nữ")) {
            rdoNu.setSelected(true);
        }
    }//GEN-LAST:event_tbl_nhanVienMouseClicked

    private void txttimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttimCaretUpdate

    }//GEN-LAST:event_txttimCaretUpdate

    private void txttimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String hoten = txttim.getText();
            ArrayList<NhanVienViewModel> kq = service.sreach(hoten);
            getDta(kq);

            ArrayList<NhanVienViewModel> list1 = service.getAll();
            //        ArrayList<NhanVienViewModel> list2 = new ArrayList<>();
            //        for (NhanVienViewModel nv : list1) {
            //            if(nv.getHoTen().equalsIgnoreCase(hoten)){
            //                list2.add(nv);
            //                this.getDta(list2);
            //            }
            //        }

            if (hoten.equals("")) {
                this.getDta(list1);
            }
        }

    }//GEN-LAST:event_txttimKeyReleased

    private void btnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQRActionPerformed
        ReadQR readQR = new ReadQR();
        readQR.setVisible(true);
        String s = readQR.getText();
        String[] s2 = s.split("\\|");

        if (s.contains("|")) {
            String cccd = s2[0];
            String hoTen = s2[2];
            String ngaySinh = s2[3];
            String ngay = ngaySinh.substring(0, 2);
            String thang = ngaySinh.substring(2, 4);
            String nam = ngaySinh.substring(4, ngaySinh.length());
            String ngayThangNam = nam + "-" + thang + "-" + ngay;
            String gioiTinh = s2[4];
            String diaChi = s2[5];

            txtCCCD.setText(cccd);
            txtDiaChi.setText(diaChi);
            txtHoTen.setText(hoTen);
            txtNgaySinh.setText(ngayThangNam);
            if (gioiTinh.equalsIgnoreCase("nam")) {
                rdoNam.setSelected(true);
            } else {
                rdoNu.setSelected(true);
            }

        } else {

            System.out.println(s);

            return;
        }
    }//GEN-LAST:event_btnQRActionPerformed

    private void btnAddNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNhanVienActionPerformed
        if (txtHoTen.getText().equals("") || txtHoTen.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống tên");
            return;
        }
        if (txtDiaChi.getText().equals("") || txtDiaChi.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống địa chỉ");
            return;
        }
        if (txtSDT.getText().equals("") || txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống số điện thoại");
            return;
        }
        if (txtNgaySinh.getText() == null || txtNgaySinh.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày sinh");
            return;
        }
        if (txtCCCD.getText() == null || txtCCCD.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống CCCD");
            return;
        }
        if (txtEmail.getText() == null || txtEmail.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày Email");
            return;
        }

        NhanVien nv = new NhanVien();
        //Validate họ tên
        if (txtHoTen.getText().matches("^[A-Za-zÀ-ỹ\\s'-]+$")) {
            nv.setHoTen(txtHoTen.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Họ tên chỉ có chữ cái và khoảng trắng");
            return;
        }

        //validate ngày sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        try {
            Date ngaySinh = dateFormat.parse(txtNgaySinh.getText());
            Date ngayHienTai = new Date();

            if (ngaySinh.after(ngayHienTai)) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không được sau ngày hiện tại.");
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh nhập chưa đúng định dạng (yyyy-MM-dd)");
            return;
        }
        if (txtNgaySinh.getText().matches("^(19[7-9]\\d|20\\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
            nv.setNgaySinh(txtNgaySinh.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Ngày sinh bắt đầu từ 1970 đến hiện tại!");
            return;
        }

        if (rdoNam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }
        //Validate số điện thoại
        if (txtSDT.getText().matches("^(03[2-9]|05[0-9]|07[0-9]|08[1-9]|09[0-9])\\d{7}$")) {
            nv.setSdt(txtSDT.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Số điện thoại nhập chưa đúng(đầu số 03, 05, 07, 08, hoặc 09 và có 10 số)");
            return;
        }
        ArrayList<NhanVienViewModel> list = service.getAll();
        for (NhanVienViewModel nvc : list) {
            if (nvc.getSdt().equals(txtSDT.getText())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại trong hệ thống");
                return;
            }
        }
        //Validate CCCD
        if (txtCCCD.getText().matches("^[0-9]{12}$")) {
            nv.setCccd(txtCCCD.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Căn cước công dân phải nhập 12 số");
            return;
        }

        for (NhanVienViewModel nvc : list) {
            if (nvc.getCccd().equals(txtCCCD.getText())) {
                JOptionPane.showMessageDialog(this, "Căn cước công dân đã tồn tại trong hệ thống");
                return;
            }
        }

        nv.setDiaChi(txtDiaChi.getText().trim());
        //validate email
        if (txtEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            nv.setEmail(txtEmail.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Email nhập chưa đúng");
            return;
        }
        for (NhanVienViewModel nvc : list) {
            if (nvc.getEmail().equals(txtEmail.getText())) {
                JOptionPane.showMessageDialog(this, "Email đã tồn tại trong hệ thống!");
                return;
            }
        }

        if (rdoDangLamViec.isSelected()) {
            nv.setTrangThai(0);
        } else {
            nv.setTrangThai(1);
        }
        nv.setMatKhau(txtMatKhau.getText());
        nv.setChucVu(String.valueOf(cbbChucVu.getSelectedItem()));

        service.them(nv);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        getDta(service.getAll());
        Clear();


    }//GEN-LAST:event_btnAddNhanVienActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id = lbID2.getText();
        if (lbID2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy chọn nhân viên cần sửa");
            return;
        }
        if (txtHoTen.getText().equals("") || txtHoTen.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống tên");
            return;
        }
        if (txtDiaChi.getText().equals("") || txtDiaChi.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống địa chỉ");
            return;
        }
        if (txtSDT.getText().equals("") || txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống số điện thoại");
            return;
        }
        if (txtNgaySinh.getText() == null || txtNgaySinh.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày sinh");
            return;
        }
        if (txtCCCD.getText() == null || txtCCCD.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống CCCD");
            return;
        }
        if (txtEmail.getText() == null || txtEmail.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày Email");
            return;
        }

        NhanVien nv = new NhanVien();
        //Validate họ tên
        if (txtHoTen.getText().matches("^[A-Za-zÀ-ỹ\\s'-]+$")) {
            nv.setHoTen(txtHoTen.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Họ tên chỉ có chữ cái và khoảng trắng");
            return;
        }

        //validate ngày sinh
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        try {
            Date ngaySinh = dateFormat.parse(txtNgaySinh.getText());
            Date ngayHienTai = new Date();

            if (ngaySinh.after(ngayHienTai)) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không được sau ngày hiện tại.");
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh nhập chưa đúng định dạng (yyyy-MM-dd)");
            return;
        }
        if (txtNgaySinh.getText().matches("^(19[7-9]\\d|20\\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
            nv.setNgaySinh(txtNgaySinh.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Ngày sinh bắt đầu từ 1970 đến hiện tại!");
            return;
        }

        if (rdoNam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }
        //Validate số điện thoại
        if (txtSDT.getText().matches("^(03[2-9]|05[0-9]|07[0-9]|08[1-9]|09[0-9])\\d{7}$")) {
            nv.setSdt(txtSDT.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Số điện thoại nhập chưa đúng(đầu số 03, 05, 07, 08, hoặc 09 và có 10 số)");
            return;
        }
        ArrayList<NhanVienViewModel> list = service.getAll();
        if (!txtSDT.getText().equals(sdt)) {
            for (NhanVienViewModel nvc : list) {
                if (nvc.getSdt().equals(txtSDT.getText())) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại trong hệ thống");
                    return;
                }
            }
        }
        //Validate CCCD
        if (txtCCCD.getText().matches("^[0-9]{12}$")) {
            nv.setCccd(txtCCCD.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Căn cước công dân phải nhập 12 số");
            return;
        }
        if (!txtCCCD.getText().equals(cccd)) {
            for (NhanVienViewModel nvc : list) {
                if (nvc.getCccd().equals(txtCCCD.getText())) {
                    JOptionPane.showMessageDialog(this, "Căn cước công dân đã tồn tại trong hệ thống");
                    return;
                }
            }
        }
        nv.setDiaChi(txtDiaChi.getText().trim());
        //validate email
        if (txtEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            nv.setEmail(txtEmail.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Email nhập chưa đúng");
            return;
        }
        if (!txtEmail.getText().equals(email)) {
            for (NhanVienViewModel nvc : list) {
                if (nvc.getEmail().equals(txtEmail.getText())) {
                    JOptionPane.showMessageDialog(this, "Email đã tồn tại trong hệ thống!");
                    return;
                }
            }
        }
        if (rdoDangLamViec.isSelected()) {
            nv.setTrangThai(0);
        } else {
            nv.setTrangThai(1);
        }
        nv.setMatKhau(txtMatKhau.getText());
        nv.setChucVu(String.valueOf(cbbChucVu.getSelectedItem()));

        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?");
        if (xacNhan == 0) {

            service.update(nv, id);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            getDta(service.getAll());
            Clear();

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = lbID2.getText();
        if (lbID2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy chọn nhân viên cần xóa");
            return;
        }
        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xác nhận xóa?", JOptionPane.YES_NO_OPTION);
        if (xacNhan == 0) {

            int check = service.delete(id);

            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Không thể xóa!");

            } else {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                getDta(service.getAll());
                Clear();
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
        getDta(service.getAll());
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed

    }//GEN-LAST:event_cbbChucVuActionPerformed

    private void rdoDangLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDangLamViecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDangLamViecActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wordkbook = new XSSFWorkbook();
            XSSFSheet sheet = wordkbook.createSheet("danhsach");
            XSSFRow row = null;
            Cell cell = null;
            //        row=sheet.createRow(0);
            //        cell=row.createCell(0,CellType.STRING);
            //        cell.setCellValue("DANH SACH KHACH HANG");
            //
            //        row=sheet.createRow(1);
            //        cell=row.createCell(0,CellType.STRING);
            //        cell.setCellValue("STT");
            //
            //        cell=row.createCell(1,CellType.STRING);
            //        cell.setCellValue("ID");
            //
            //        cell=row.createCell(2,CellType.STRING);
            //        cell.setCellValue("MA");
            //
            //        cell=row.createCell(3,CellType.STRING);
            //        cell.setCellValue("HOTEN");
            //
            //        cell=row.createCell(4,CellType.STRING);
            //        cell.setCellValue("NGAYSINH");
            //
            //        cell=row.createCell(5,CellType.STRING);
            //        cell.setCellValue("GIOITINH");
            //
            //        cell=row.createCell(6,CellType.STRING);
            //        cell.setCellValue("SDT");
            //
            //        cell=row.createCell(7,CellType.STRING);
            //        cell.setCellValue("DIACHI");
            //
            //        cell=row.createCell(8,CellType.STRING);
            //        cell.setCellValue("EMAIL");

            list = service.getAll();
            for (int i = 0; i < list.size(); i++) {
                //Modelbook book =arr.get(i);
                row = sheet.createRow(i);

                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(list.get(i).getId().toString());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(list.get(i).getMaNv());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(list.get(i).getHoTen());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(list.get(i).getGioiTinh());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(list.get(i).getNgaySinh());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(list.get(i).getSdt());

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(list.get(i).getCccd());

                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue(list.get(i).getDiaChi());

                cell = row.createCell(9, CellType.STRING);
                cell.setCellValue(list.get(i).getEmail());

                cell = row.createCell(10, CellType.STRING);
                cell.setCellValue(list.get(i).getChucVu());

                cell = row.createCell(11, CellType.STRING);
                cell.setCellValue(list.get(i).getTrangThai());
            }

            File f = new File("D://danhsachNV.xlsx");
            try {
                FileOutputStream fis = new FileOutputStream(f);
                wordkbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();

            } catch (IOException ex) {
                ex.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "in thanh cong D:\\danhsach");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi mo file");
        }
    }//GEN-LAST:event_btninActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNhanVien;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQR;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbID2;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JRadioButton rdoDangLamViec;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiViec;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tbl_nhanVien;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
